const url ={
    BASE_URL:"https://localhost:7174/api",
    ADMIN:{
        LOGIN:"/Admin/login",
        REGISTER:"/Admin/register",
        PROFILE:"/Admin/profile",
    },
    FRAME:{
        LIST:"/Frame",
        CREATE:"/Frame",
        EDIT:"/Frame",
        DELETE:"/Frame",
        GET:"/Frame/get-by-id"
    },
    SIZE:{
        LIST:"/Size",
        CREATE:"/Size",
        EDIT:"/Size",
        DELETE:"/Size",
        GET:"/Size/get-by-id"
    },
    HANGER:{
        LIST:"/Hanger",
        CREATE:"/Hanger",
        EDIT:"/Hanger",
        DELETE:"/Hanger",
        GET:"/Hanger/get-by-id"
    },
    ORDER:{
        LIST:"/Order",
        CREATE:"/Order",
        UPDATEORDER:"/Order/UpdateOrder",
        CANCELORDER:"/Order/CancelOrder",
        GET:"/Order/get-by-id",
        GET_ORDER_CANCELLED:"Order/get-order-cancelled",
        GET_ORDER_WAITTING:"Order/get-order-waitting",
        GET_ORDER_CONFIRMED:"Order/get-order-confirmed",
        GET_ORDER_SHIPPING:"Order/get-order-shipping",
        GET_ORDER_SHIPPED:"Order/get-order-shipped",
        GET_ORDER_SUCCESSED:"Order/get-order-successed",
        GET_ORDER_TODAY:"Order/today-orders",
        GET_AMOUNT_TODAY:"Order/today-orders-amount",
        GET_AMOUNT_YESTERDAY:"Order/yesterday-orders-amount",
        GET_AMOUNT_TWODAYSAGO:"Order/2-days-ago-orders-amount",
        GET_AMOUNT_THREEDAYSAGO:"Order/3-days-ago-orders-amount",
        GET_AMOUNT_FOURDAYSAGO:"Order/4-days-ago-orders-amount",
        GET_AMOUNT_FIVEDAYSAGO:"Order/5-days-ago-orders-amount",
        GET_AMOUNT_SIXDAYSAGO:"Order/6-days-ago-orders-amount",
        GET_AMOUNT_MONTH1:"Order/month1-orders-amount",
        GET_AMOUNT_MONTH2:"Order/month2-orders-amount",
        GET_AMOUNT_MONTH3:"Order/month3-orders-amount",
        GET_AMOUNT_MONTH4:"Order/month4-orders-amount",
        GET_AMOUNT_MONTH5:"Order/month5-orders-amount",
        GET_AMOUNT_MONTH6:"Order/month6-orders-amount",
        GET_AMOUNT_MONTH7:"Order/month7-orders-amount",
        GET_AMOUNT_MONTH8:"Order/month8-orders-amount",
        GET_AMOUNT_MONTH9:"Order/month9-orders-amount",
        GET_AMOUNT_MONTH10:"Order/month10-orders-amount",
        GET_AMOUNT_MONTH11:"Order/month11-orders-amount",
        GET_AMOUNT_MONTH12:"Order/month12-orders-amount",
        GET_ORDER_DAYSAGO:"Order/get-orders-days-ago"
    },
    ORDERIMAGE:{
        LIST:"/OrderImage",
        CREATE:"/OrderImage",
        GET:"/OrderImage/get-by-order-id"
    },
    USER:{
        LIST:"/User",
        REGISTER:"/User/register",
        LOGIN:"/User/login",
        PROFILE:"/User/profile",
    }
}
export default url;